# Generated by Django 3.1.3 on 2022-02-21 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220221_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='pickeup_address',
            new_name='pickup_address',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='pickeup_lat',
            new_name='pickup_lat',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='pickeup_lng',
            new_name='pickup_lng',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='pickeup_name',
            new_name='pickup_name',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='pickeup_phone',
            new_name='pickup_phone',
        ),
    ]
